version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "pip "
    versioning-strategy: increase-if-necessary